// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:prio/data/models/reminder.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PriorityLevelAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(ReminderTypeAdapter());
    registerAdapter(RepeatIntervalAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PriorityLevelAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(ReminderTypeAdapter());
    registerAdapter(RepeatIntervalAdapter());
  }
}
